services:
  db:
    image: mysql:8.0
    container_name: gg-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wp}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: gg-wordpress
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${MYSQL_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wp}
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gg-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER:-wp}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-wp}
    ports:
      - "8081:80"

volumes:
  db_data:
  wp_data:
