import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gang Ground",
  description: "Generated by create next app",
};

function ThemeInitScript() {
  // Runs before hydration to avoid theme flash
  const code = `(() => {
    try {
      const key = 'theme';
      let t = localStorage.getItem(key);
      if (!t) {
        t = (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light';
      }
      const root = document.documentElement;
      if (t === 'dark') root.classList.add('theme-dark');
      else root.classList.remove('theme-dark');
    } catch (_) {}
  })();`;
  return <script dangerouslySetInnerHTML={{ __html: code }} />;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeInitScript />
      </head>
      <body className={`${montserrat.className}`}>
        <Header />
        {children}
        <Navigation />
      </body>
    </html>
  );
}
